# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookWindow(object):
    def setupUi(self, BookWindow):
        BookWindow.setObjectName("BookWindow")
        BookWindow.resize(535, 600)
        BookWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(BookWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lastButton = QtWidgets.QPushButton(self.centralwidget)
        self.lastButton.setObjectName("lastButton")
        self.gridLayout.addWidget(self.lastButton, 1, 0, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        BookWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BookWindow)
        self.statusbar.setObjectName("statusbar")
        BookWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(BookWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 535, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        BookWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(BookWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(BookWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(BookWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(BookWindow)
        QtCore.QMetaObject.connectSlotsByName(BookWindow)

    def retranslateUi(self, BookWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lastButton.setText(_translate("BookWindow", "<"))
        self.nextButton.setText(_translate("BookWindow", ">"))
        self.menu.setTitle(_translate("BookWindow", "Формат текста"))
        self.action.setText(_translate("BookWindow", "Выбрать шрифт"))
        self.action_2.setText(_translate("BookWindow", "Сменить размер"))
        self.action_3.setText(_translate("BookWindow", "Цвет текста"))
