# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookWindow(object):
    def setupUi(self, BookWindow):
        BookWindow.setObjectName("BookWindow")
        BookWindow.resize(535, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BookWindow.sizePolicy().hasHeightForWidth())
        BookWindow.setSizePolicy(sizePolicy)
        BookWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(BookWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 2)
        BookWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BookWindow)
        self.statusbar.setObjectName("statusbar")
        BookWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(BookWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 535, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        BookWindow.setMenuBar(self.menuBar)
        self.Choice_font_action = QtWidgets.QAction(BookWindow)
        self.Choice_font_action.setObjectName("Choice_font_action")
        self.Choice_size_action = QtWidgets.QAction(BookWindow)
        self.Choice_size_action.setObjectName("Choice_size_action")
        self.Choice_text_color_action = QtWidgets.QAction(BookWindow)
        self.Choice_text_color_action.setObjectName("Choice_text_color_action")
        self.menu.addAction(self.Choice_font_action)
        self.menu.addAction(self.Choice_size_action)
        self.menu.addAction(self.Choice_text_color_action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(BookWindow)
        QtCore.QMetaObject.connectSlotsByName(BookWindow)

    def retranslateUi(self, BookWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menu.setTitle(_translate("BookWindow", "Формат текста"))
        self.Choice_font_action.setText(_translate("BookWindow", "Выбрать шрифт"))
        self.Choice_size_action.setText(_translate("BookWindow", "Сменить размер"))
        self.Choice_text_color_action.setText(_translate("BookWindow", "Цвет текста"))
